// Mocks generated by Mockito 5.4.6 from annotations
// in aeroporto_clima_app/test/aeroporto_busca_controller_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i5;
import 'dart:ui' as _i8;

import 'package:aeroporto_clima_app/controllers/aeroporto_clima_controller.dart'
    as _i6;
import 'package:aeroporto_clima_app/models/aeroporto_clima_model.dart' as _i2;
import 'package:aeroporto_clima_app/services/cptec_service.dart' as _i3;
import 'package:get/get.dart' as _i4;
import 'package:get/get_state_manager/src/simple/list_notifier.dart' as _i7;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeAeroportoClima_0 extends _i1.SmartFake
    implements _i2.AeroportoClima {
  _FakeAeroportoClima_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeCptecService_1 extends _i1.SmartFake implements _i3.CptecService {
  _FakeCptecService_1(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeRxBool_2 extends _i1.SmartFake implements _i4.RxBool {
  _FakeRxBool_2(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeRxString_3 extends _i1.SmartFake implements _i4.RxString {
  _FakeRxString_3(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeRxn_4<T> extends _i1.SmartFake implements _i4.Rxn<T> {
  _FakeRxn_4(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeInternalFinalCallback_5<T> extends _i1.SmartFake
    implements _i4.InternalFinalCallback<T> {
  _FakeInternalFinalCallback_5(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [CptecService].
///
/// See the documentation for Mockito's code generation for more information.
class MockCptecService extends _i1.Mock implements _i3.CptecService {
  MockCptecService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i5.Future<_i2.AeroportoClima> fetchClimaAeroporto(String? icaoCode) =>
      (super.noSuchMethod(
        Invocation.method(
          #fetchClimaAeroporto,
          [icaoCode],
        ),
        returnValue: _i5.Future<_i2.AeroportoClima>.value(_FakeAeroportoClima_0(
          this,
          Invocation.method(
            #fetchClimaAeroporto,
            [icaoCode],
          ),
        )),
      ) as _i5.Future<_i2.AeroportoClima>);
}

/// A class which mocks [AeroportoClimaController].
///
/// See the documentation for Mockito's code generation for more information.
class MockAeroportoClimaController extends _i1.Mock
    implements _i6.AeroportoClimaController {
  MockAeroportoClimaController() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.CptecService get service => (super.noSuchMethod(
        Invocation.getter(#service),
        returnValue: _FakeCptecService_1(
          this,
          Invocation.getter(#service),
        ),
      ) as _i3.CptecService);

  @override
  _i4.RxBool get isLoading => (super.noSuchMethod(
        Invocation.getter(#isLoading),
        returnValue: _FakeRxBool_2(
          this,
          Invocation.getter(#isLoading),
        ),
      ) as _i4.RxBool);

  @override
  _i4.RxString get errorMessage => (super.noSuchMethod(
        Invocation.getter(#errorMessage),
        returnValue: _FakeRxString_3(
          this,
          Invocation.getter(#errorMessage),
        ),
      ) as _i4.RxString);

  @override
  _i4.Rxn<_i2.AeroportoClima> get climaCache => (super.noSuchMethod(
        Invocation.getter(#climaCache),
        returnValue: _FakeRxn_4<_i2.AeroportoClima>(
          this,
          Invocation.getter(#climaCache),
        ),
      ) as _i4.Rxn<_i2.AeroportoClima>);

  @override
  set isLoading(_i4.RxBool? value) => super.noSuchMethod(
        Invocation.setter(
          #isLoading,
          value,
        ),
        returnValueForMissingStub: null,
      );

  @override
  set errorMessage(_i4.RxString? value) => super.noSuchMethod(
        Invocation.setter(
          #errorMessage,
          value,
        ),
        returnValueForMissingStub: null,
      );

  @override
  set climaCache(_i4.Rxn<_i2.AeroportoClima>? value) => super.noSuchMethod(
        Invocation.setter(
          #climaCache,
          value,
        ),
        returnValueForMissingStub: null,
      );

  @override
  _i4.InternalFinalCallback<void> get onStart => (super.noSuchMethod(
        Invocation.getter(#onStart),
        returnValue: _FakeInternalFinalCallback_5<void>(
          this,
          Invocation.getter(#onStart),
        ),
      ) as _i4.InternalFinalCallback<void>);

  @override
  _i4.InternalFinalCallback<void> get onDelete => (super.noSuchMethod(
        Invocation.getter(#onDelete),
        returnValue: _FakeInternalFinalCallback_5<void>(
          this,
          Invocation.getter(#onDelete),
        ),
      ) as _i4.InternalFinalCallback<void>);

  @override
  bool get initialized => (super.noSuchMethod(
        Invocation.getter(#initialized),
        returnValue: false,
      ) as bool);

  @override
  bool get isClosed => (super.noSuchMethod(
        Invocation.getter(#isClosed),
        returnValue: false,
      ) as bool);

  @override
  bool get hasListeners => (super.noSuchMethod(
        Invocation.getter(#hasListeners),
        returnValue: false,
      ) as bool);

  @override
  int get listeners => (super.noSuchMethod(
        Invocation.getter(#listeners),
        returnValue: 0,
      ) as int);

  @override
  void onInit() => super.noSuchMethod(
        Invocation.method(
          #onInit,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  _i5.Future<bool> fetchAndSaveClima(String? icaoCode) => (super.noSuchMethod(
        Invocation.method(
          #fetchAndSaveClima,
          [icaoCode],
        ),
        returnValue: _i5.Future<bool>.value(false),
      ) as _i5.Future<bool>);

  @override
  _i5.Future<void> loadSavedClima() => (super.noSuchMethod(
        Invocation.method(
          #loadSavedClima,
          [],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<void> clearSavedClima() => (super.noSuchMethod(
        Invocation.method(
          #clearSavedClima,
          [],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  void update([
    List<Object>? ids,
    bool? condition = true,
  ]) =>
      super.noSuchMethod(
        Invocation.method(
          #update,
          [
            ids,
            condition,
          ],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void onReady() => super.noSuchMethod(
        Invocation.method(
          #onReady,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void onClose() => super.noSuchMethod(
        Invocation.method(
          #onClose,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void $configureLifeCycle() => super.noSuchMethod(
        Invocation.method(
          #$configureLifeCycle,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  _i7.Disposer addListener(_i7.GetStateUpdate? listener) => (super.noSuchMethod(
        Invocation.method(
          #addListener,
          [listener],
        ),
        returnValue: () {},
      ) as _i7.Disposer);

  @override
  void removeListener(_i8.VoidCallback? listener) => super.noSuchMethod(
        Invocation.method(
          #removeListener,
          [listener],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void refresh() => super.noSuchMethod(
        Invocation.method(
          #refresh,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void refreshGroup(Object? id) => super.noSuchMethod(
        Invocation.method(
          #refreshGroup,
          [id],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void notifyChildrens() => super.noSuchMethod(
        Invocation.method(
          #notifyChildrens,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void removeListenerId(
    Object? id,
    _i8.VoidCallback? listener,
  ) =>
      super.noSuchMethod(
        Invocation.method(
          #removeListenerId,
          [
            id,
            listener,
          ],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void dispose() => super.noSuchMethod(
        Invocation.method(
          #dispose,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  _i7.Disposer addListenerId(
    Object? key,
    _i7.GetStateUpdate? listener,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #addListenerId,
          [
            key,
            listener,
          ],
        ),
        returnValue: () {},
      ) as _i7.Disposer);

  @override
  void disposeId(Object? id) => super.noSuchMethod(
        Invocation.method(
          #disposeId,
          [id],
        ),
        returnValueForMissingStub: null,
      );
}
